### ISSUE TITLE
Support sending from different (authorized) email

### ISSUE THREAD

**Issue by lookprzybylski** [hmiladhia/Dmail#1]
Hello, I really appreciate your work. I found an issue that library (gmail api) does not allow to send emails with different FROM value as it's always set to `sender_email`.
If I authorize at google with account X which is capable of sending emails on behalf of Y (set in gmail/settings/accounts) it's not possible to send emails as Y because Y goes into API url instead of X.
Api response if I set Y as a sender_email is:
```
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://gmail.googleapis.com/gmail/v1/users/Y@gmail.com/messages/send?alt=json returned "Delegation denied for X@gmail.com". Details: "[{'message': 'Delegation denied for X@gmail.com', 'domain': 'global', 'reason': 'forbidden'}]">
```

Quick and dirty fix to show that it's possible is to set Y in FROM field of the message:
```
sender_email = 'X@gmail.com'
from_email = 'Y@gmail.com'

def set_header_patch(email_instance, from_email):
    def add_header(key, value):
        if value:
            try:
                email_instance.message.replace_header(key, value)
            except KeyError:
                email_instance.message.add_header(key, value)

    def set_header(to=None, subject=None, cc=None, bcc=None, **kwargs):
        add_header("From", from_email)
        add_header('Subject', subject)
        add_header('cc', ','.join(email_instance._recipient_to_list(cc)))
        add_header("To", ','.join(email_instance._recipient_to_list(to)))
    return set_header


with GmailApi(sender_email, 'token.pickle', cred) as email:
    email._set_header = set_header_patch(email, from_email)
    email.send(message, recipient_email, subject='Test')
```

It's certainly possible to fix this many ways, I don't know your code well enough to create a pull request but it would be nice if you consider adding this feature in next release.

Regards

**Comment by hmiladhia** [comment]
Hello, Thank you for your feedback. I'm glad you like the library.
I've added the requested feature. To use it you can do the following:

```python
with GmailApi(sender_email, 'token.pickle', cred) as email:
    email.send(message, recipient_email, subject='Test', sender=from_email)
```
I will merge it in master and include it in the next release :) !
